name: Nightly Smoke Tests

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  smoke_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: dev

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Install Python deps
        run: pip install .[obj,dev]

      - name: Install Linode CLI
        run: make install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run smoke tests
        run: |
          make smoketest
        env:
          LINODE_CLI_TOKEN: ${{ secrets.LINODE_TOKEN_2 }}
